spring:
  application:
    name: auth
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    org:
      springframework:
        security: TRACE